apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: webapp-certificate
spec:
  secretName: default-tls
  issuerRef:
    name: letsencrypt-dns01-issuer
    kind: ClusterIssuer
  commonName: linuxeval.eu.org
  dnsNames:
  - linuxeval.eu.org
  - '*.linuxeval.eu.org'
